platform :ios, '6.0'
pod 'AFNetworking', '2.5.4'
pod 'Reachability'
pod 'JsonModel'
pod 'RegexKitLite'
pod 'MBProgressHUD'
pod 'MBAlertView'
pod 'SDWebImage'
pod 'MagicPie'
pod 'GDataXML-HTML'
pod 'SSZipArchive'